env:
  jest: true
  node: true
root: true
plugins:
  - import
  - prettier
parserOptions:
  ecmaVersion: 2021
  sourceType: module
extends:
  - plugin:prettier/recommended
  - prettier
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript
rules:
  prettier/prettier:
    - error
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - "**/test/**"
        - "**/build-tools/**"
      optionalDependencies: false
      peerDependencies: true
  import/no-unresolved:
    - error
  import/order:
    - warn
    - groups:
        - builtin
        - external
      alphabetize:
        order: asc
        caseInsensitive: true
  no-duplicate-imports:
    - error
  no-shadow:
    - off
  key-spacing:
    - error
  no-multiple-empty-lines:
    - error
  no-return-await:
    - off
  no-trailing-spaces:
    - error
  dot-notation:
    - error
  no-bitwise:
    - error
overrides:
  - files:
      - '**/*.ts'
    parser: '@typescript-eslint/parser'
    parserOptions:
      ecmaVersion: 2021
      sourceType: module
      project: ./tsconfig.json
    extends:
      - plugin:@typescript-eslint/recommended
    rules:
      '@typescript-eslint/no-require-imports':
        - error
      "@typescript-eslint/return-await":
        - error
      "@typescript-eslint/no-shadow":
        - error
      "@typescript-eslint/no-floating-promises":
        - error
      "@typescript-eslint/member-ordering":
        - error
        - default:
          - public-static-field
          - public-static-method
          - protected-static-field
          - protected-static-method
          - private-static-field
          - private-static-method
          - field
          - constructor
          - method

